version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/usr/local/apache2/htdocs/